### ISSUE TITLE
Is this different from Sadtalker?

### ISSUE THREAD

**Issue by Inferencer** [suryanshgupta9933/Talking-Avatars#1]
Hello, I just saw your results and noticed it has implemented Sadtalker, I was wondering how this repo was different if at all

**Comment by suryanshgupta9933** [comment]
The animation part is exact code from sadtalker, but I am planning to implement/combine multiple different things such as voice cloning and TTS also image generation for avatar. Kind of like an automated AI content creation tool(that is the vision). I cleaned the sadtalker code a bit for my use case. Still a very early stage repo.
